package com.ox.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "HUA".
 */
@Entity
public class Hua {

    @Id
    private Long id;

    @NotNull
    private String name;
    private Long cityId;
    private boolean hasDrawn;

    @Generated
    public Hua() {
    }

    public Hua(Long id) {
        this.id = id;
    }

    @Generated
    public Hua(Long id, String name, Long cityId, boolean hasDrawn) {
        this.id = id;
        this.name = name;
        this.cityId = cityId;
        this.hasDrawn = hasDrawn;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    public Long getCityId() {
        return cityId;
    }

    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    public boolean getHasDrawn() {
        return hasDrawn;
    }

    public void setHasDrawn(boolean hasDrawn) {
        this.hasDrawn = hasDrawn;
    }

}
