package com.ox.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TIME_AREA".
 */
@Entity
public class TimeArea {

    @Id
    private Long id;
    private Long huaId;
    private long startTime;
    private long endTime;

    @Generated
    public TimeArea() {
    }

    public TimeArea(Long id) {
        this.id = id;
    }

    @Generated
    public TimeArea(Long id, Long huaId, long startTime, long endTime) {
        this.id = id;
        this.huaId = huaId;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getHuaId() {
        return huaId;
    }

    public void setHuaId(Long huaId) {
        this.huaId = huaId;
    }

    public long getStartTime() {
        return startTime;
    }

    public void setStartTime(long startTime) {
        this.startTime = startTime;
    }

    public long getEndTime() {
        return endTime;
    }

    public void setEndTime(long endTime) {
        this.endTime = endTime;
    }

}
